CREATE TABLE TB_TRANSACAO(
   ID_TRANSACAO NUMERIC AUTO_INCREMENT NOT NULL PRIMARY KEY,
   ID_MERCADORIA VARCHAR(5) NOT NULL,
   TP_MERCADORIA VARCHAR(20) NOT NULL,
   NM_MERCADORIA VARCHAR(100) NOT NULL,
   QT_MERCADORIA NUMERIC NOT NULL ,
   VL_TRANSACAO NUMERIC NOT NULL,
   TP_TRANSACAO VARCHAR(6) NOT NULL
) ;
